### ISSUE TITLE
error

### ISSUE THREAD

**Issue by niuniuJQKKK** [lxulxu/WatermarkRemover#1]
请问大佬，我遇到了这个问题，该怎么解决啊？。谢谢
```
Moviepy - Building video output\莫迪_no_watermark.mp4.
MoviePy - Writing audio in 莫迪_no_watermarkTEMP_MPY_wvf_snd.mp3
chunk:   0%|          | 0/1622 [00:00<?, ?it/s, now=None]Traceback (most recent call last):
  File "D:/kaifa/PycharmWork/douyin/douyin_utils/video_util.py", line 208, in <module>
    remover.remove_video_watermark()
  File "D:/kaifa/PycharmWork/douyin/douyin_utils/video_util.py", line 160, in remove_video_watermark
    self.merge_audio(name, output_path, TEMP_VIDEO)
  File "D:/kaifa/PycharmWork/douyin/douyin_utils/video_util.py", line 123, in merge_audio
    clip.write_videofile(output_path)
  File "<decorator-gen-55>", line 2, in write_videofile
  File "D:\kaifa\python\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-54>", line 2, in write_videofile
  File "D:\kaifa\python\lib\site-packages\moviepy\decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-53>", line 2, in write_videofile
  File "D:\kaifa\python\lib\site-packages\moviepy\decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "D:\kaifa\python\lib\site-packages\moviepy\video\VideoClip.py", line 293, in write_videofile
    self.audio.write_audiofile(audiofile, audio_fps,
  File "<decorator-gen-45>", line 2, in write_audiofile
  File "D:\kaifa\python\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "D:\kaifa\python\lib\site-packages\moviepy\audio\AudioClip.py", line 206, in write_audiofile
    return ffmpeg_audiowrite(self, filename, fps, nbytes, buffersize,
  File "<decorator-gen-9>", line 2, in ffmpeg_audiowrite
  File "D:\kaifa\python\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "D:\kaifa\python\lib\site-packages\moviepy\audio\io\ffmpeg_audiowriter.py", line 166, in ffmpeg_audiowrite
    for chunk in clip.iter_chunks(chunksize=buffersize,
  File "D:\kaifa\python\lib\site-packages\moviepy\audio\AudioClip.py", line 85, in iter_chunks
    yield self.to_soundarray(tt, nbytes=nbytes, quantize=quantize,
  File "<decorator-gen-44>", line 2, in to_soundarray
  File "D:\kaifa\python\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "D:\kaifa\python\lib\site-packages\moviepy\audio\AudioClip.py", line 127, in to_soundarray
    snd_array = self.get_frame(tt)
  File "<decorator-gen-11>", line 2, in get_frame
  File "D:\kaifa\python\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "D:\kaifa\python\lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "D:\kaifa\python\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 77, in <lambda>
    self.make_frame = lambda t: self.reader.get_frame(t)
  File "D:\kaifa\python\lib\site-packages\moviepy\audio\io\readers.py", line 177, in get_frame
    fr_min, fr_max = frames.min(), frames.max()
  File "D:\kaifa\python\lib\site-packages\numpy\core\_methods.py", line 43, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
TypeError: int() argument must be a string, a bytes-like object or a number, not '_NoValueType'
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Process finished with exit code 1
```

**Comment by lxulxu** [comment]
你好，可以试试 'pip install moviepy --upgrade'升级moviepy，或‘brew reinstall ffmpeg’重新安装ffmpeg，参考链接https://stackoverflow.com/questions/68032884/getting-typeerror-must-be-real-number-not-nonetype-whenever-trying-to-run-wr
